### ISSUE TITLE
License

### ISSUE THREAD

**Issue by OscarAbraham** [BrunoSilvaFreire/ShiroiUnity2DPathfinding#3]
Hi, a lot of this looks very interesting. Do you plan to release this under any specific license? Is this just for your private use? Thanks for your time :)

**Comment by BrunoSilvaFreire** [comment]
Hello! Thanks for taking your time to look into this project!

Indeed, I've actually forgot to add a License, sorry, I'll do it in a moment.

But yes! This project will be open source and free for commercial use under the MIT license!

**Comment by BrunoSilvaFreire** [comment]
If you have any other questions, please do not hesitate to re-open this issue!
And once again, thank you for your time
